import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "../componets/Navber";
import Footer from "../componets/Footer";
import 'animate.css';
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head><link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
      /></head>
      <body className="min-h-full flex flex-col">

        <Navber></Navber>

        {children}

        <Footer></Footer>



        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
